[package]
name = "dccscr-whitelists-rs"
version = "0.1.0"
edition = "2018"

[dependencies]
git2 = "0.13"
clap = "3.0.0-beta.2"

[lib]
name = "whitelists"
path = "src/lib.rs"

[[bin]]
name = "wl"
path = "src/main.rs"
